model_name_or_path: "openai/whisper-tiny"
model: "whisper-tiny"
language: "English"
language_abbr: "en"
task: "transcribe"
dataset_name: "mozilla-foundation/common_voice_11_0"
size: 0.01
#- 0.0025
#- 0.005
#- 0.01
#- 0.02
user_name: "jihaiku"
peft_type: "LoRA"
r: 32
#- 16
#- 32
#- 64
#- 128
lora_alpha: 64
#- 32
#- 64
#- 128
lora_dropout: 0.05
#- 0.01
#- 0.025
#- 0.05
bias: "none"
csv_path: "active"
json_path: null
# if you want to use json_path, put in the path of the json file to this location. "path/to/your_file.json"